### ISSUE TITLE
Correct the readme.

### ISSUE THREAD

**Issue by ashishsingh4u** [BROADSoftware/hbtools#1]
Hi Serge,

Correct the readme to refer --delValues instead of --delValue.

"If you set the switch combination  --delRows **--delValue** --updValues , this the content of the table will be ajusted to be fully identical to the content of the input file."

**Comment by SergeAlexandre** [comment]
Thanks for the info.
Will be corrected on next release (Soon)

**Comment by ashishsingh4u** [comment]
Thanks for fixing the same.
